[package]
name = "ajsteinhauser/rosa-rbx"
version = "0.2.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
homepage = "https://rosaanalytic.com/"
description = "Rosa event logging and exfil library. Automatically tracks many Roblox events + API for tracking custom events"
authors = ["AJ Steinhauser <support@rosaanalytic.com"]

[dependencies]

[dev-dependencies]
testez = "roblox/testez@0.4.1"
