[package]
name = "ajsteinhauser/rosa-rbx"
version = "0.2.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
homepage = "https://rosaanalytic.com/"
authors = ["AJ Steinhauser <support@rosaanalytic.com"]

[dependencies]

[dev-dependencies]
testez = "roblox/testez@0.4.1"
